[package]
edition = { workspace = true }
license = { workspace = true }
name = "untisgram-db"

[dependencies]
chrono = { workspace = true }
diesel = { version = "2.0", features = ["chrono", "postgres", "r2d2", "serde_json", "uuid"] }
diesel-derive-enum = { version = "2.1", features = ["postgres"] }
diesel_migrations = "2.0"
dotenvy = "0.15"
eyre = { workspace = true }
impl-tools = { workspace = true }
once_cell = { workspace = true }
r2d2 = "0.8"
restructed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }
